repos:
  - repo: https://github.com/psf/black
    rev: "24.10.0"
    hooks:
      - id: black
        #args: ['--config=.black.ini']
        language_version: python3
  - repo: https://github.com/PyCQA/flake8
    rev: "5.0.4"
    hooks:
      - id: flake8
  - repo: https://github.com/timothycrosley/isort
    rev: "5.11.5"
    hooks:
      - id: isort
        #args: ['--settings-path=.isort.cfg']
  - repo: https://github.com/PyCQA/bandit
    rev: "1.8.0"
    hooks:
      - id: bandit
        args: ["--configfile=pyproject.toml", "--recursive", "-a=file"]
